add resource documentation for Global Surface Water
mapme-initiative/mapme.biodiversity pull request #239
Opened 2024-02-14 13:04 UTC by karpfen

This PR adds the missing GSW documentation, s. https://github.com/mapme-initiative/mapme.biodiversity/issues/234

2024-02-14 13:06 UTC, goergen95 commented
Hi @karpfen, thanks! I think this also applies to the indicators. Would you mind revising them as well and include it in this PR?

2024-02-15 09:42 UTC, karpfen commented
@goergen95 I added the calc_gsw_* function docs now.

2024-02-15 14:01 UTC, karpfen commented
I just found a typo, I'll fix it before the merge

2024-02-16 09:46 UTC, goergen95 requested changes
Hi @karpfen, 

I added some comments that I would like to ask you to take care of. Once this is done, docu-wise this PR looks good. 

However, I just realized a fact that was not so clear to me before. The indicator routines do not actually estimate some definition of surface water area. I think this is actually the indicator that people are interested in. So, I think we need to find an approach similar to GFW, that will estimate some definition of surface water area based on user-defined thresholds in the future. Maybe you already have some ideas?

Not sure how to best handle this, but I guess that would be a new PR.

2024-02-16 09:46 UTC, goergen95 commented on R/calc_gsw_change.R
> +#' The following arguments can be set:
This part does not render correctly, please revise.

2024-02-16 09:46 UTC, goergen95 commented on R/get_gsw.R
> +#' Global Surface Water Change
Could you please add the scientific reference of this data set? Also I would suggest to write a common paragraph (2 or 3 sentences) of the general background of the data (e.g. calculated by JRC based on ...) and repeat that for all resources before going into the details of that specific resource.

2024-02-16 09:46 UTC, goergen95 commented on R/get_gsw.R
> +#' @format Global raster layers
Is this one global raster layer? For esalandcover we write: "A global tiled raster resource available for years 2015 to 2019." Could you please adjust?

2024-02-19 12:23 UTC, merged